name: Push Developer Branch
on:
  push:
    branches-ignore:
      - master
      - main
      - dev
      - staging
      - release/**
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: echo "Developer Branch Push!"